# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rbtree-pure 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rbtree-pure"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Victor Costan"]
  s.date = "2014-09-26"
  s.description = "This is a pure-ruby implementation of the rbtree gem."
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".project",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/rbtree-pure.rb",
    "lib/rbtree/guard_node.rb",
    "lib/rbtree/multi_rb_tree.rb",
    "lib/rbtree/node.rb",
    "lib/rbtree/rb_tree.rb",
    "lib/rbtree/tree.rb",
    "lib/rbtree/tree_cmp.rb",
    "rbtree-pure.gemspec",
    "test/helper.rb",
    "test/multi_rbtree_test.rb",
    "test/rbtree_test.rb"
  ]
  s.homepage = "http://github.com/pwnall/rbtree-pure"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.1"
  s.summary = "Pure-ruby implementation of red-black trees."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
  end
end

